"""
Configuration constants for the game.
"""

WIDTH = 800
HEIGHT = 600
FPS = 60

DEFAULT_AMMO = 10
DEFAULT_TIME = 30.0
MAX_TARGETS_ON_SCREEN = 3
TARGET_RADIUS = 25.0
CROSSHAIR_SPEED = 250.0 # pixels per second
MASTER_VOLUME = 1.0 # 0.0 to 1.0

# Bootstrap & Game Engine settings
GAME_TITLE = "BlindSpot Duel"
INITIAL_STATE = "AUTH_SCREEN"
DEFAULT_BG_MUSIC = "background"

# Database & Logging settings
DB_PATH = "game_data.db"
LEADERBOARD_LIMIT = 10
LOG_FILE_PATH = "game_errors.log"
LOG_LEVEL = "INFO"
LOG_FORMAT = '%(asctime)s [%(levelname)s] %(message)s'

# Gameplay rules & Target types parameters
DEFAULT_BASE_SCORE = 3
ITEM_RADIUS = 20.0
ITEM_BASE_SCORE = 1
AMMO_BOX_BONUS = 5
TIME_BOOST_BONUS = 5.0

# Sound effects naming mapping
SFX_SHOOT = "shoot"
SFX_HIT = "hit"
SFX_MISS = "miss"
SFX_POWERUP = "powerup"

# Grid drawing parameters
GRID_SPACING = 40
GRID_LINE_WIDTH = 1

# Concentric neon glows & border thickness parameters
GLOW_DIVISOR = 4
GLOW_RADIUS_OFFSET = 4
GLOW_RING_WIDTH = 2
ENTITY_BORDER_WIDTH = 2
CENTER_DOT_RADIUS = 2

# Text rendering details
FONT_NAME = "Courier New"
FONT_SHADOW_OFFSET = 2
DEFAULT_FONT_SIZE = 24

# HUD details and styling configurations
HUD_MARGIN_X = 20
HUD_MARGIN_Y = 20
HUD_BOX_WIDTH = 300
HUD_BOX_HEIGHT = 80
HUD_BORDER_RADIUS = 5
HUD_BORDER_WIDTH = 1
HUD_TEXT_OFFSET_X = 10
HUD_COMBO_OFFSET_X = 120
HUD_TIME_BAR_WIDTH = 180
HUD_TIME_BAR_HEIGHT = 10
HUD_TIME_BAR_OFFSET_X = 10
HUD_TIME_BAR_OFFSET_Y = 46
HUD_TIME_TEXT_OFFSET_X = 10
HUD_TIME_TEXT_OFFSET_Y = -2
HUD_AMMO_DOT_SPACING = 10
HUD_AMMO_DOT_RADIUS = 3
HUD_AMMO_DOT_OFFSET_X = 45
HUD_AMMO_DOT_OFFSET_Y = 6
HUD_GLITCH_TEXT_OFFSET_Y = -12

# Verification configurations
MAX_USERNAME_LEN = 12
MAX_PASSWORD_LEN = 15
ALLOWED_CHARS = "_-@."

# Auth layout configurations
AUTH_BOX_WIDTH = 460
AUTH_BOX_HEIGHT = 240
AUTH_BOX_X = 400
AUTH_BOX_Y = 180
AUTH_BOX_BORDER_RADIUS = 6
AUTH_INPUT_BORDER_RADIUS = 4

# Leaderboard layout configurations
LEADERBOARD_BOX_X = 120
LEADERBOARD_BOX_Y = 130
LEADERBOARD_BOX_WIDTH = 560
LEADERBOARD_BOX_HEIGHT = 380
LEADERBOARD_BOX_BORDER_RADIUS = 6
LEADERBOARD_ROW_Y_START = 65
LEADERBOARD_ROW_Y_SPACING = 28

# Menu Screen layout & particle configurations
MENU_PARTICLE_COUNT = 30
MENU_PARTICLE_VX_RANGE = (-10.0, 10.0)
MENU_PARTICLE_VY_RANGE = (-15.0, -5.0)
MENU_PARTICLE_RADIUS_RANGE = (1.0, 3.0)
MENU_PULSE_SPEED = 0.005
MENU_PULSE_AMPLITUDE = 15.0
MENU_OPTIONS_Y_START = 290
MENU_OPTIONS_Y_SPACING = 65
MENU_BTN_WIDTH = 280
MENU_BTN_HEIGHT = 44
MENU_BTN_BORDER_RADIUS = 4

# Playing Screen specific configs
P1_START_POS = (WIDTH / 4.0, HEIGHT / 2.0)
P2_START_POS = (3 * WIDTH / 4.0, HEIGHT / 2.0)
VFX_TEXT_OFFSET_X = -15
VFX_TEXT_OFFSET_Y = -30
TARGET_RING_RATIO = 0.7
TARGET_RING_WIDTH = 2
TARGET_INNER_RATIO = 0.3
AMMO_BOX_BORDER_RADIUS = 4
ITEM_LABEL_OFFSET_Y = -8
ITEM_LABEL_SIZE = 11
TIME_BOOST_BORDER_WIDTH = 2
TIME_BOOST_HAND_1_OFFSET_Y = -12
TIME_BOOST_HAND_2_OFFSET_X = 8
TIME_BOOST_HANDS_WIDTH = 2
GLITCH_DEBUFF_LABEL_SIZE = 14
GLITCH_DEBUFF_LABEL_OFFSET_Y = -2
RETICLE_RADIUS = 12
RETICLE_LINE_WIDTH = 1
RETICLE_LINE_OUTER = 18
RETICLE_LINE_INNER = 4
RETICLE_CENTER_RADIUS = 2

# Visual Effects parameters
VFX_SHOCKWAVE_MAX_RADIUS = 50.0
VFX_SHOCKWAVE_SPEED = 120.0
VFX_SHOCKWAVE_START_RADIUS = 5.0
VFX_SHOCKWAVE_WIDTH = 2
VFX_DEFAULT_SPEED = 50.0
VFX_DEFAULT_DURATION = 1.0
VFX_SPAWN_SPEED = 40.0
VFX_SPAWN_DURATION = 0.8
VFX_FONT_SIZE = 18
VFX_SHADOW_OFFSET = (1, 1)
VFX_EXPLOSION_COUNT = 15
VFX_EXPLOSION_SPEED_RANGE = (30.0, 100.0)
VFX_EXPLOSION_SIZE_RANGE = (2.0, 5.0)
VFX_EXPLOSION_LIFETIME_RANGE = (0.3, 0.6)

import sys
import os

if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    BASE_DIR = sys._MEIPASS
else:
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Resource loading details
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
SOUNDS_SUBDIR = "sounds"
IMAGES_SUBDIR = "images"
FALLBACK_IMAGE_SIZE = (50, 50)
FALLBACK_IMAGE_RADIUS = 25
